name: Windows Release

on:
  push:
    branches:
      - 'master'
      - 'continuous-integration'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'continuous-integration'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.0
  ARTIFACT:     qt-widgets-build.zip

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python  # Use Python 3.10 to avoid compatibility issues
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies  # Install aqt and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall

      - name: Install Qt with aqt using MSVC
        run: |
          python -m aqt install-qt windows desktop ${{ env.QT_VERSION }} win64_msvc2022_64

      - name: Create build directory
        run: mkdir ${{ runner.temp }}\build

      - name: Set up MSVC environment
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Build
        working-directory: ${{ runner.temp }}\build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}\qtaction.pro
          nmake -j2
          cd release
          windeployqt6 qtaction.exe --pdb --release --compiler-runtime

      - name: Zip build
        working-directory: ${{ runner.temp }}
        run: 7z a qt-widgets-build.zip ${{ runner.temp }}\build\* -r

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
