name: Windows Release

on:
  push:
    branches:
      - 'master'
      - 'continuous-integration'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'continuous-integration'

defaults:
  run:
    shell: cmd  # We are using CMD shell, so we need to use CMD-style variable expansion

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.0  # Qt version is set here
  ARTIFACT:     qt-widgets-build.zip

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python  # Use Python 3.10 to avoid compatibility issues
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies  # Install aqt and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall

      - name: Install Qt with aqt  # Install Qt using aqt and use correct CMD variable substitution
        run: |
          python -m aqt install-qt windows desktop %QT_VERSION% mingw_64

      - name: Create build directory
        run: mkdir %RUNNER_TEMP%\build

      - name: Set up MinGW environment
        run: |
          SET PATH=C:\Qt\Tools\mingw1120_64\bin;%PATH%
          SET PATH=C:\Qt\6.7.0\mingw_64\bin;%PATH%

      - name: Build
        working-directory: %RUNNER_TEMP%\build
        run: |
          qmake -r %SOURCE_DIR%\qtaction.pro
          mingw32-make -j2
          cd release
          windeployqt6 qtaction.exe --pdb --release --compiler-runtime

      - name: Zip build
        working-directory: %RUNNER_TEMP%
        run: 7z a qt-widgets-build.zip %RUNNER_TEMP%\build\* -r

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: %ARTIFACT%
          path: %RUNNER_TEMP%\%ARTIFACT%
