name: Windows Release

on:
  push:
    branches:
      - 'master'
      - 'continuous-integration'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'continuous-integration'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.0
  ARTIFACT:     qt-widgets-build.zip

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python  # Use Python 3.10 to avoid compatibility issues
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies  # Install aqt and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aqtinstall

      - name: Install Qt with aqt  # Install Qt using aqt and use correct variable substitution
        run: |
          python -m aqt install-qt windows desktop ${{ env.QT_VERSION }} mingw_64

      - name: Create build directory
        run: mkdir ${{ runner.temp }}\build

      - name: Set up MinGW environment
        run: |
          SET PATH=C:\Qt\Tools\mingw1120_64\bin;%PATH%
          SET PATH=C:\Qt\${{ env.QT_VERSION }}\mingw_64\bin;%PATH%

      - name: Build
        working-directory: ${{ runner.temp }}\build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}\qtaction.pro
          mingw32-make -j2
         
